In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
l1=[1,2,3,4]
l2=[5,6,7,8]
l3=[[1,2,3],[4,5,6],[7,8,9]]
print(l1+l2)

#arrays

a=np.array(l1)
b=np.array(l2)
print(a+b)

#data type using type()

print(type(l3))

#multiplication, Division

print(np.matmul(a,a))
print(np.divide(a,a))
print(np.power(a,2))
print("addition of two arrays :",a+b)


print(np.sin(a))
print(np.log(b))
print(np.log2(a))
print(np.exp(a))


# Given data
people = ['kiran', 'arun', 'vijay', 'varun']
age = [25, 30, 35, 40]
height = [145, 151, 165, 173]
weight = [45, 55, 65, 75]

# Creating a DataFrame
healthcare_data = pd.DataFrame({
    'Name': people,
    'Age': age,
    'Height': height,
    'Weight': weight
})

# 3. Scatter Plot
plt.figure(figsize=(8, 6))
plt.scatter(healthcare_data['Age'], healthcare_data['Weight'], color='blue')
plt.title('Scatter Plot of Age vs Weight')
plt.xlabel('Age')
plt.ylabel('Weight')

# 4. Bar Chart
plt.figure(figsize=(8, 6))
plt.bar(healthcare_data['Name'], healthcare_data['Height'], color='green')
plt.title('Bar Chart of Height for Each Person')
plt.xlabel('Name')
plt.ylabel('Height')

# 5. Histogram
plt.figure(figsize=(8, 6))
plt.hist(healthcare_data['Weight'], bins=10, color='orange', edgecolor='black')
plt.title('Histogram of Weight Distribution')
plt.xlabel('Weight')
plt.ylabel('Frequency')










[1, 2, 3, 4, 5, 6, 7, 8]
[ 6  8 10 12]
<class 'list'>
30
[1. 1. 1. 1.]
[ 1  4  9 16]
addition of two arrays : [ 6  8 10 12]
[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[1.60943791 1.79175947 1.94591015 2.07944154]
[0.        1.        1.5849625 2.       ]
[ 2.71828183  7.3890561  20.08553692 54.59815003]
